version: '3'
services:
  javaserver1:
    build:
      context: ./payaramicro_javaproject
  javaserver2:
    build:
      context: ./payaramicro_javaproject
  javaserver3:
    build:
      context: ./payaramicro_javaproject
  loadbalancer:
    build:
      context: ./loadbalancer
    depends_on:
      - javaserver1
      - javaserver2
      - javaserver3
    ports:
     - "80:80"
